# fly.toml app configuration file generated for api-ffhockey-sur-gazon on 2025-10-25T09:13:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-ffhockey-sur-gazon'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
