#!/bin/bash
# QUICK START - Déploiement Fly.io (3 étapes, 10 minutes)

echo "🚀 DÉMARRAGE RAPIDE - Déploiement Fly.io"
echo "========================================"
echo ""
echo "📋 PRÉ-REQUIS:"
echo "  ✓ Compte Fly.io (https://fly.io)"
echo "  ✓ flyctl installé (brew install flyctl)"
echo "  ✓ Firebase_key.json dans le dossier"
echo ""

# ÉTAPE 1
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ÉTAPE 1️⃣  - Déployer l'API sur Fly.io"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Commandes:"
echo "  fly auth login"
echo "  ./deploy-flyio.sh"
echo ""
read -p "Appuyez ENTRER une fois le déploiement terminé..."

# ÉTAPE 2
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ÉTAPE 2️⃣  - Build le Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Commandes:"
echo "  cd Dashboard"
echo "  npm run build"
echo "  # Vérifier que le dossier 'dist' est créé"
echo ""
read -p "Appuyez ENTRER une fois le build terminé..."

# ÉTAPE 3
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ÉTAPE 3️⃣  - Déployer le Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A - NETLIFY (recommandé):"
echo "  1. Aller sur https://app.netlify.com"
echo "  2. Drag & drop le dossier 'dist'"
echo "  3. Configurer env var VITE_API_URL:"
echo "     https://api-ffhockey-sur-gazon.fly.dev"
echo ""
echo "Ou Option B - VERCEL:"
echo "  1. Connecter votre repo GitHub"
echo "  2. Configurer VITE_API_URL en env var"
echo "  3. Deploy!"
echo ""
read -p "Appuyez ENTRER une fois le Dashboard déployé..."

echo ""
echo "✅ DÉPLOIEMENT TERMINÉ!"
echo ""
echo "🔗 URLs:"
echo "  • API: https://api-ffhockey-sur-gazon.fly.dev"
echo "  • Dashboard: https://votre-url-netlify.app"
echo ""
echo "🎮 Tester:"
echo "  1. Ouvrir le Dashboard"
echo "  2. Sélectionner 'Elite Hommes'"
echo "  3. Cliquer 'Importer matchs'"
echo "  4. Voir les 50+ vrais matchs s'afficher ! 🏒"
echo ""
echo "📝 Documentation:"
echo "  • DEPLOYMENT_FLYIO.md - Guide complet"
echo "  • DEPLOYMENT_SUMMARY.md - Résumé"
